### ISSUE TITLE
Class missing 

### ISSUE THREAD

**Issue by sha-z6912** [camunda-community-hub/camunda-8-examples#334]
![image](https://github.com/camunda-community-hub/camunda-8-examples/assets/51782921/0ac2630c-625f-4910-ba7e-02554f6c2190)
Project used - Dmn springboot
What did not work out - class missing
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: C:\apache-maven-3.9.6
Java version: 17.0.10, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

**Comment by jonathanlukas** [comment]
Hello @sha-z6912 , the referenced class does not exist in this repository at all. Could you please point me to the point in the code where the class `org.camunda.community.examples.dmn.TwitterExampleApplication` is?
